[package]
name = "fmat_manu"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.34.1"
strum = "0.27.2"
strum_macros = "0.27"
libmath = "0.2.1"
bit-vec = "0.8"
lazy_static = "1.5.0"

[profile.profiling]
inherits = "release"
debug = true